/*

 GAME_OVER_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 10 x 7
   Tile set      :
 Z:\var\home\matthew\Documents\Projects\flappy-gb\res\game_over.gbr Plane count
 : 1 plane (8 bits) Plane order   : Tiles are continues Tile offset   : 0 Split
 data    : No

 This file was generated by GBMB v1.8

*/

#pragma once

#include "defines.h"

#define GAME_OVER_MAPWidth 10
#define GAME_OVER_MAPHeight 7
#define GAME_OVER_MAPBank 0

extern const unsigned char GAME_OVER_MAP[];

/* End of GAME_OVER_MAP.H */
