/*

 MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 31 x 17
   Tile set      : Z:\var\home\matthew\Documents\Projects\flappy-gb\res\bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#pragma once

#define BG_TILE_MAPWidth 32
#define BG_TILE_MAPHeight 18
#define BG_TILE_MAPBank 0

extern const unsigned char BG_TILE_MAP[];

/* End of MAP.H */
