/*

 EXPORT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#pragma once
#include "defines.h"

/* Bank of tiles. */
#define NUMERALS_TILE_DATABank 0
/* Start of tile array. */
extern const unsigned char NUMERALS_TILE_DATA[];
extern const unsigned char NUMERALS_TILE_MAP[];
extern const unsigned char NUMERALS_TILE_CLEAR[];
/* End of EXPORT.H */
