/*

 EXPORT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#pragma once

/* Bank of tiles. */
#define BUTTON_TILE_DATABank 0
/* Start of tile array. */
extern const unsigned char BUTTON_TILE_DATA[];

/* End of EXPORT.H */
