#pragma once
#include <gb/gb.h>

#define TILE_SIZE 8
#define GRAVITY_ACCELERATION 1
#define APPLY_GRAVITY_N_FRAMES 4
#define CYCLE_ANIMATION_N_FRAMES 8
#define JUMP_VELOCITY -4
#define BACKGROUND_SCROLL_SPEED 1
#define FOREGROUND_SCROLL_SPEED 2
#define PIPE_TILE_START 9
#define NUMERALS_TILE_START 10
#define BLANK_NUMERAL_TILE 20
#define PIPE_WIDTH 24
#define BUTTON_TILE_START 14
#define CYCLE_BUTTON_N_FRAMES 16
#define WINDOW_CENTERING_OFFSET 23
#define GAME_OVER_TILE_START 21

#define BIRD_WIDTH 16
#define BIRD_HEIGHT 12

typedef INT8 ScreenCoordinate;
